apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-lwm2m
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: LwM2M Device
    driverImage: lwm2m-device:v0.0.1
#    available instructions
  instructions: |
    instructions:
      temperature:
        protocolPropertyList:
          DataFormat: PlainText
          ObjectId: /3303/0/5700
          EnableObserve: true
