name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: get latest tag
        id: get_latest_tag
        run: | 
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "NEW_TAG=${latest_tag}" >> "$GITHUB_ENV"
        env:
          GITHUB_ENV: ${{ env.GITHUB_ENV }}
      
      - name: determine if pre-release
        id: determine_pre_release
        run: |
          # day_of_week=$(date +%u)
          # if [ "$day_of_week" -eq 4 ]; then
          #   echo "::set-output name=PRE_RELEASE::true"
          # else
          #   echo "::set-output name=PRE_RELEASE::false"
          # fi
          minute=$(( $(date +%M) % 10 ))
          if [ "$minute" -ge 5 ]; then
            echo "::set-output name=PRE_RELEASE::true"
          else
            echo "::set-output name=PRE_RELEASE::false"
          fi

      - name: read changelog content
        id: read_changelog
        run: |
          changelog_content="## See [CHANGELOG-v0.x.0.md](CHANGELOG/CHANGELOG-v0.x.0.md) for details
                             ## 详细内容请查看 [CHANGELOG-v0.x.0-zh.md](CHANGELOG/CHANGELOG-v0.x.0-zh.md)"
          echo "::set-output name=CHANGELOG_CONTENT::${changelog_content}"

      - name: create release
        run: |
          release_tag="${{ env.NEW_TAG }}"
          echo "${release_tag}"
          changelog_content= ${{ steps.read_changelog.outputs.CHANGELOG_CONTENT }}
          echo "${changelog_content}"
          pre_release="${{ steps.determine_pre_release.outputs.PRE_RELEASE }}"
          echo "${pre_release}"
          if [ "$pre_release" == "true" ]; then
            gh release create "$release_tag" \
              --target main \
              --title "$release_tag" \
              --generate-notes \
              --prerelease
          else
            gh release create "$release_tag" \
              --target main \
              --title "$release_tag" \
              --notes "$changelog_content"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}