name: Handle Merged PR

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_tag_and_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=LATEST_TAG::${latest_tag}"

      - name: create new branch and tag
        run: |
          current_tag="${{ steps.get_latest_tag.outputs.LATEST_TAG }}"
          current_version=$(echo "${current_tag}" | cut -d'.' -f2)
          next_version=$((current_version + 1))
          new_tag="v0.${next_version}.0"
          branch_name="new_feature_branch"
          git checkout main
          git pull
          git checkout -b $branch_name
          make tag VERSION=${new_tag}-rc1
          git commit -am "change tag for release ${new_tag}-rc1"
          git push origin $branch_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
